### ISSUE TITLE
starter card allowed in hand.

### ISSUE THREAD

**Issue by dbjock** [phoughton/cribbage_scorer#2]
I'm new to cribbage, and have only played 2 handed and not sure if cribbage can be played with a double deck. Is it intentional to allow the show card, to be included in the hand for scoring?

This came to my attention in the sample provided that the show card, and the first card in the hand are the same, the 5 of diamonds.
```
starter = (5, "D")
hand = [(5, "D"), (5, "S"), (5, "C"), (11, "D")]
```
This would only occur with a double deck.
Are the plans for the back end calculations to catch this and provide feed back, or should the interface to the functions catch that?

**Comment by phoughton** [comment]
Hello @dbjock, yeah this example is wrong, thanks for highlighting it.
I will add validation to catch these sorts of issues, I had expected the calling apps to validate - but I think that's externalizing behaviour that would be better kept in the library. This would avoid the sort of confusion we see here. 
AFAIK cribbage is a one pack game.
Thanks.

**Comment by phoughton** [comment]
This was fixed in the latest release.
The scorer will now throw an exception when there are duplicate cards.
